### ISSUE TITLE
When to release code and datasets?

### ISSUE THREAD

**Issue by BeastyZ** [init0xyz/AdaCQR#1]
Great work!

Very pleased to see such excellent work! It has been 2 months since your first public paper was published. When will the code and datasets be open sourced?

**Comment by init0xyz** [comment]
Hi, I'm glad to see your comment. The code and datasets of AdaCQR will be publicly available upon acceptance. If you have any questions about AdaCQR, you can contact me by email: yilong.lai@seu.edu.cn or wechat: init0xyz.

Thanks again for your comment.

**Comment by BeastyZ** [comment]
Thank you very much for your prompt and kind reply, as well as for providing your personal contact information. I will patiently await the release of your code. Best wishes for the acceptance of your paper.
